### ISSUE TITLE
Support for AdminThemeDefault

### ISSUE THREAD

**Issue by matjazpotocnik** [Toutouwai/SelectizeAll#3]
Hi! This is how it looks in AdminThemeDefault:

![image](https://user-images.githubusercontent.com/7663992/233797964-e3b87b87-63ce-4cb4-8723-47a421e4c636.png)

I guess you don't plan to support admin themes other than AdminThemeUikit?

**Comment by Toutouwai** [comment]
Only AdminThemeUikit is supported, which is mentioned in the readme.
