### ISSUE TITLE
If installed, RepeaterMatrix "Show Settings" gets automatically toggled

### ISSUE THREAD

**Issue by jlahijani** [Toutouwai/SelectizeAll#4]
Thanks for creating this module.  It saves a lot of time.

I noticed that if it is installed with the default settings, a repeater matrix item will automatically have its "Type" field (which is normally activated by clicking the gear icon on the matrix item) pre-toggled.  It also breaks clicking the gear icon to hide the field.

See attached screenshot.
![Screenshot 2023-12-20 081817](https://github.com/Toutouwai/SelectizeAll/assets/4558/56b2529b-a605-4cfe-9731-8c92faf02b13)

**Comment by Toutouwai** [comment]
Thanks, should be fixed by latest commit.
